name: homemind
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+10

environment:
  sdk: ^3.8.1
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^16.0.0
  provider: ^6.1.5
  shared_preferences: ^2.5.3
  get_it: ^8.0.3
  flutter_dotenv: ^5.2.1
  graphql_flutter: ^5.2.0
  reactive_forms: ^18.1.1
  rxdart: ^0.28.0
  flutter_svg: ^2.2.0
  jiffy: ^6.4.3
  geolocator: ^14.0.2
  dotted_border: ^3.1.0
  flutter_blue_plus: ^1.35.5
  socket_io_client: ^3.1.2
  flutter_typeahead: ^5.2.0
  infinite_scroll_pagination: ^5.1.0
  ui_common:
    git: https://github.com/brocodev/ui_common.git
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6
  cryptography: ^2.7.0
  flutter_secure_storage: ^9.2.4
  local_auth: ^2.3.0
  uuid: ^4.5.1
  package_info_plus: ^8.3.1
  firebase_core: ^4.1.0
  firebase_messaging: ^16.0.1
  flutter_local_notifications: ^19.4.2
  cached_network_image: ^3.4.1
  flutter_inappwebview: ^6.1.5
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  sliding_up_panel: ^2.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  graphql_codegen: ^1.2.4
  build_runner: ^2.5.4
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  rename_app: ^1.6.5
  change_app_package_name: ^1.5.0

flutter:
  uses-material-design: true
  assets:
    - assets/config/
    - assets/images/favourite.png
    - assets/images/login.png
    - assets/images/background.png
    - assets/images/device.png
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/images/weather/
    - assets/images/settings/
    - assets/icons/svg/
    - assets/Lottie/
    - assets/icons/menu_icons/
    - assets/images/movies/
    - assets/brands/

  fonts:
    - family: "Noto Sans"
      fonts:
        - asset: "assets/fonts/NotoSans-Bold.ttf"
          style: "normal"
        - asset: "assets/fonts/NotoSans-Regular.ttf"
          style: "normal"
    - family: "Poppins"
      fonts:
        - asset: "assets/fonts/Poppins-700.ttf"
          style: "normal"
          weight: 700
    - family: ABeeZee
      fonts:
        - asset: assets/fonts/ABeeZee-Italic.ttf
          style: italic
        - asset: assets/fonts/ABeeZee-Regular.ttf
          style: normal
    - family: Lexend
      fonts:
        - asset: assets/fonts/Lexend-Medium.ttf
          weight: 500
        - asset: assets/fonts/Lexend-ExtraLight.ttf
          weight: 200

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/brands/logo_app.png"
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF"   # màu nền cho adaptive icon Android
  adaptive_icon_foreground: "assets/brands/logo_app.png"

flutter_native_splash:
  color: "#ffffff"                # màu background (vd: trắng)
  image: assets/brands/splash_app.png  # logo splash
  android: true
  ios: true
  web: false
  android_12:
    image: assets/brands/splash_app.png
    color: "#ffffff"