// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyw6ft2iDYcHskPEOgs1W-sW4lvRY2Up0',
    appId: '1:1012555142627:web:66786e2d9af1e60c767cd6',
    messagingSenderId: '1012555142627',
    projectId: 'ht-stg-f450b',
    authDomain: 'ht-stg-f450b.firebaseapp.com',
    storageBucket: 'ht-stg-f450b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8c-Be7vNs_QvL9b_3fMphzmwgmzhOMi4',
    appId: '1:1012555142627:android:5fa471462c5c8cbe767cd6',
    messagingSenderId: '1012555142627',
    projectId: 'ht-stg-f450b',
    storageBucket: 'ht-stg-f450b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDK1zBpmgPNxeo_fzd4lFECI44eBIphrj4',
    appId: '1:1012555142627:ios:5012b99608484aac767cd6',
    messagingSenderId: '1012555142627',
    projectId: 'ht-stg-f450b',
    storageBucket: 'ht-stg-f450b.firebasestorage.app',
    iosBundleId: 'htezlife.co.vn.homemind',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDK1zBpmgPNxeo_fzd4lFECI44eBIphrj4',
    appId: '1:1012555142627:ios:3f07a7031c480ddb767cd6',
    messagingSenderId: '1012555142627',
    projectId: 'ht-stg-f450b',
    storageBucket: 'ht-stg-f450b.firebasestorage.app',
    iosBundleId: 'htezlife.co.vn.htezlife',
  );

}